---
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: extension
build:
  insecureRegistries:
    - garden.local.gardener.cloud:5001
  tagPolicy:
    customTemplate:
      template: "{{.version}}-{{.sha}}"
      components:
        - name: version
          envTemplate:
            template: "{{.EXTENSION_VERSION}}"
        # inputDigest is used to inject a digest of the artifact source into the built image tag
        # and therefore into the SKAFFOLD_IMAGE environment variable which is used when generating the corresponding ControllerDeployment
        - name: sha
          inputDigest: {}
  artifacts:
    - image: local-skaffold/gardener-extension-shoot-oidc-service
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-shoot-oidc-service
            - cmd/gardener-extension-shoot-oidc-service/app
            - imagevector
            - imagevector/images.yaml
            - pkg/apis/config
            - pkg/apis/config/v1alpha1
            - pkg/cmd
            - pkg/constants
            - pkg/controller/healthcheck
            - pkg/controller/lifecycle
            - pkg/controller/lifecycle/templates/authentication.gardener.cloud_openidconnects.yaml
            - pkg/secrets
            - pkg/webhook/kapiserver
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-shoot-oidc-service
      hooks:
        after:
          - command: ["sh", "hack/skaffold-image.sh"]
manifests:
  kustomize:
    paths:
    - local-setup
resourceSelector:
  # instruct skaffold to inject the built image reference into the image field in our ControllerDeployment
  allow:
    - groupKind: ControllerDeployment.core.gardener.cloud
      image:
        - .helm.values.image.ref
deploy:
  # --server-side apply is a workaround for https://github.com/gardener/gardener/issues/10267.
  # kubectl apply attempts a strategic merge patch which fails for a ControllerDeployment.
  # For more details, see https://github.com/gardener/gardener/issues/10267.
  #
  # TODO: Switch back to "kubectl: {}" when the above issue is resolved.
  kubectl:
    flags:
      apply:
        - --server-side
        - --force-conflicts
