#!/usr/bin/env bash

COMPONENT_PREFIXES="eu.gcr.io/gardener-project/gardener/oidc-webhook-authenticator" \
    "$(dirname $0)"/../vendor/github.com/gardener/gardener/hack/.ci/component_descriptor "$(dirname $0)"/..
