name: Prepare Release

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    - name: make-generate
      shell: bash
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        make generate
