apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: local-wl
  namespace: garden-local
spec:
  extensions:
  - type: shoot-oidc-service
  cloudProfileName: local
  region: local
  provider:
    type: local
