ocm:
  component_name: github.com/gardener/garden-shoot-trust-configurator
  component_version: v0.3.0
release_notes:
- audience: dependency
  author:
    hostname: github.com
    type: githubUser
    username: dependabot[bot]
  category: other
  contents: |-
    The following third party dependencies have been updated:
    - github.com/gardener/gardener v1.141.1 -> v1.142.0
    - github.com/Masterminds/semver/v3 v3.4.0 -> v3.5.0
    - go.yaml.in/yaml/v2 v2.4.3 -> v2.4.4
  mimetype: text/markdown
  reference: '[#118](https://github.com/gardener/garden-shoot-trust-configurator/pull/118)'
  type: standard
- audience: dependency
  author:
    hostname: github.com
    type: githubUser
    username: dependabot[bot]
  category: other
  contents: |-
    The following third party dependencies have been updated:
    - github.com/gardener/gardener v1.144.0 -> v1.144.1
    - github.com/gardener/gardener/pkg/apis v1.144.0 -> v1.144.1
  mimetype: text/markdown
  reference: '[#127](https://github.com/gardener/garden-shoot-trust-configurator/pull/127)'
  type: standard
- audience: dependency
  author:
    hostname: github.com
    type: githubUser
    username: vpnachev
  category: other
  contents: |-
    The following third party dependencies have been updated:
    - github.com/aws/aws-sdk-go-v2 v1.41.7 -> v1.42.0
    - github.com/aws/aws-sdk-go-v2/config v1.32.17 -> v1.32.25
    - github.com/aws/aws-sdk-go-v2/credentials v1.19.16 -> v1.19.24
    - github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.18.23 -> v1.18.29
    - github.com/aws/aws-sdk-go-v2/internal/configsources v1.4.23 -> v1.4.29
    - github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.7.23 -> v2.7.29
    - github.com/aws/aws-sdk-go-v2/internal/v4a v1.4.24 -> v1.4.30
    - github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.13.9 -> v1.13.12
    - github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.13.23 -> v1.13.29
    - github.com/aws/aws-sdk-go-v2/service/signin v1.0.11 -> v1.2.0
    - github.com/aws/aws-sdk-go-v2/service/sso v1.30.17 -> v1.31.3
    - github.com/aws/aws-sdk-go-v2/service/ssooidc v1.35.21 -> v1.36.6
    - github.com/aws/aws-sdk-go-v2/service/sts v1.42.1 -> v1.43.3
    - github.com/aws/smithy-go v1.25.1 -> v1.27.2
    - github.com/go-openapi/errors v0.22.7 -> v0.22.8
    - github.com/zitadel/oidc/v3 v3.45.4 -> v3.47.5
    - go.opentelemetry.io/contrib/otelconf v0.23.0 -> v0.24.0
    - go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc v0.19.0 -> v0.20.0
    - go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp v0.19.0 -> v0.20.0
    - go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.43.0 -> v1.44.0
    - go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v1.43.0 -> v1.44.0
    - go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.43.0 -> v1.44.0
    - go.opentelemetry.io/otel/exporters/prometheus v0.65.0 -> v0.66.0
    - go.opentelemetry.io/otel/exporters/stdout/stdoutlog v0.19.0 -> v0.20.0
    - go.opentelemetry.io/otel/exporters/stdout/stdoutmetric v1.43.0 -> v1.44.0
    - go.opentelemetry.io/otel/exporters/stdout/stdouttrace v1.43.0 -> v1.44.0
    - go.opentelemetry.io/otel/log v0.19.0 -> v0.20.0
    - go.opentelemetry.io/otel/sdk/log v0.19.0 -> v0.20.0
    - k8s.io/autoscaler/vertical-pod-autoscaler v1.6.0 -> v1.7.0
    - k8s.io/kube-aggregator v0.35.5 -> v0.36.2
    - k8s.io/metrics v0.35.5 -> v0.36.2
    - sigs.k8s.io/gateway-api v1.5.0 -> v1.5.1
  mimetype: text/markdown
  reference: '[#130](https://github.com/gardener/garden-shoot-trust-configurator/pull/130)'
  type: standard
- audience: operator
  author:
    hostname: github.com
    type: githubUser
    username: dependabot[bot]
  category: other
  contents: Component binaries are now built with Go 1.26.3
  mimetype: text/markdown
  reference: '[#117](https://github.com/gardener/garden-shoot-trust-configurator/pull/117)'
  type: standard
- audience: operator
  author:
    hostname: github.com
    type: githubUser
    username: dependabot[bot]
  category: other
  contents: Component binaries are now built with Go 1.26.4
  mimetype: text/markdown
  reference: '[#124](https://github.com/gardener/garden-shoot-trust-configurator/pull/124)'
  type: standard
- audience: dependency
  author:
    hostname: github.com
    type: githubUser
    username: dependabot[bot]
  category: other
  contents: |-
    The following third party dependencies have been updated:
    - github.com/gardener/gardener v1.142.1 -> v1.142.2
    - github.com/gardener/gardener/pkg/apis v1.142.1 -> v1.142.2
  mimetype: text/markdown
  reference: '[#121](https://github.com/gardener/garden-shoot-trust-configurator/pull/121)'
  type: standard
