name: Non-Release
on:
  push:
    branches:
    - master
    - 'release-v*'
  pull_request_target:
    types:
      - labeled

jobs:
  build:
    # only run if run was triggered by either:
    # - head-update (push to local branch)
    # - pullrequest-label `reviewed/ok-to-test` was added
    # (the latter label is hardcoded in gardener/cc-utils's trusted-checkout action)
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'reviewed/ok-to-test' }}
    uses: ./.github/workflows/build.yaml
    with:
      mode: snapshot
    secrets: inherit
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write # needed for un-labelling

  component-descriptor:
    uses: gardener/cc-utils/.github/workflows/post-build.yaml@master
    needs:
      - build
    secrets: inherit
    permissions:
      id-token: write
      contents: write
