name: Update Gardener
on:
  push:
    branches:
    - dependabot/go_modules/gardener-*
permissions: write-all
jobs:
  run:
    name: Run make tidy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: get-go-version
      id: go-version
      shell: bash
      run: |
        version=$(grep -oP 'FROM.*golang:\K[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)
        echo "version=$version" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-go@v7
      with:
        go-version: ${{ steps.go-version.outputs.version }}

    - name: Make tidy
      run: make tidy
    - name: Commit changes
      run: |
        # Exit early if there is nothing to commit. This can happen if someone pushes to the dependabot's PR (for example has to adapt to a breaking change).
        if [[ -z $(git status --porcelain) ]]; then
          echo "Nothing to commit, working tree clean. Exiting..."
          exit 0
        fi

        git config user.name gardener-robot-ci-1
        git config user.email gardener.ci.user@gmail.com
        git add .
        git commit --signoff -m "[dependabot skip] make tidy"
        git push origin
